import type { FileMap } from '@/lib/projects/types';

export function getDefaultRunEntry(files: FileMap): string | null {
  if (files['run.js']) return 'run.js';
  if (files['script.js']) return 'script.js';

  // If user has a node entry
  const candidates = ['index.js', 'main.js', 'app.js'];
  for (const c of candidates) {
    if (files[c]) return c;
  }

  // If they only have HTML, we can't execute node script directly.
  return null;
}

export function buildNodeRunShim(entryPath: string) {
  return `// Auto-generated by FinalCode\n// This file is used to run your chosen JS file inside WebContainers.\n\nimport './${entryPath}';\n`;
}
