import type { FileMap } from '@/lib/projects/types';

export function getDefaultRunEntry(files: FileMap): string | null {
  // For fullstack apps, prioritize server entry points
  if (files['server.js']) return 'server.js';
  
  // Check for common entry points
  if (files['run.js']) return 'run.js';
  if (files['script.js']) return 'script.js';

  // If user has a node entry
  const candidates = ['index.js', 'main.js', 'app.js'];
  for (const c of candidates) {
    if (files[c]) return c;
  }

  // If they only have HTML, we can't execute node script directly.
  return null;
}

export function buildNodeRunShim(entryPath: string) {
  return `// Auto-generated by FinalCode\n// This file is used to run your chosen JS file inside WebContainers.\n\nimport './${entryPath}';\n`;
}

export function isFullstackProject(files: FileMap): boolean {
  // Check for backend indicators
  if (files['server.js'] || files['app.js']?.includes('express')) return true;
  
  // Check package.json for backend dependencies
  if (files['package.json']) {
    try {
      const pkg = JSON.parse(files['package.json']);
      const deps = { ...pkg.dependencies, ...pkg.devDependencies };
      const backendPkgs = ['express', 'fastify', 'koa', 'hapi', 'restify'];
      if (backendPkgs.some(p => p in deps)) return true;
    } catch {
      // ignore parse errors
    }
  }
  
  // Check for backend file structure
  const hasRoutes = Object.keys(files).some(f => f.startsWith('routes/'));
  const hasMiddleware = Object.keys(files).some(f => f.startsWith('middleware/'));
  const hasDb = Object.keys(files).some(f => f.startsWith('db/'));
  
  return hasRoutes || hasMiddleware || hasDb;
}

export function getServerStartCommand(files: FileMap): string[] {
  // Check package.json for start script
  if (files['package.json']) {
    try {
      const pkg = JSON.parse(files['package.json']);
      if (pkg.scripts?.start) {
        return ['npm', 'run', 'start'];
      }
      if (pkg.scripts?.dev) {
        return ['npm', 'run', 'dev'];
      }
    } catch {
      // ignore
    }
  }
  
  // Default to running server.js directly
  const entry = getDefaultRunEntry(files);
  if (entry) {
    return ['node', entry];
  }
  
  return ['node', 'server.js'];
}

export function needsNpmInstall(files: FileMap): boolean {
  if (!files['package.json']) return false;
  
  try {
    const pkg = JSON.parse(files['package.json']);
    const deps = pkg.dependencies || {};
    const devDeps = pkg.devDependencies || {};
    return Object.keys(deps).length > 0 || Object.keys(devDeps).length > 0;
  } catch {
    return false;
  }
}
